import Head from 'next/head';
import styled from 'styled-components';
import ChatBox from '../components/ChatBox';
import NavBar from '../components/NavBar';
import SideBar from '../components/SideBar';
import ChatProvider from '../providers/ChatProvider';
import UserProvider from '../providers/UserProvider';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <UserProvider>
      <ChatProvider>
        <AppContainer>
          
          <Head>
            <title>WhatsApp 2.0</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <NavBar/>

          <Container>
            <SideBar />
            <ChatBox />
          </Container>

        </AppContainer>
      </ChatProvider>
    </UserProvider>
  )
}

const AppContainer = styled.main`
  background-color: #ececec;
  min-height: 100vh;
`

const Container = styled.div`
  max-width: 980px;
  margin: auto;
  display: flex;
  width: 100%;
  min-height: calc(100vh - 80px);
`
